#ifndef TFLITE_OPS_TO_REGISTER_H_
#define TFLITE_OPS_TO_REGISTER_H_

// Selective registration header for SecureEdgeMobile
// Include only operators required by blazeface and mobilefacenet models

#define TFLITE_REG_ABS_SUPPORTED
#define TFLITE_REG_ADD_SUPPORTED
#define TFLITE_REG_CONCATENATION_SUPPORTED
#define TFLITE_REG_CONV_2D_SUPPORTED
#define TFLITE_REG_DEPTHWISE_CONV_2D_SUPPORTED
#define TFLITE_REG_DEQUANTIZE_SUPPORTED
#define TFLITE_REG_L2_NORMALIZATION_SUPPORTED
#define TFLITE_REG_MAX_POOL_2D_SUPPORTED
#define TFLITE_REG_MUL_SUPPORTED
#define TFLITE_REG_PAD_SUPPORTED
#define TFLITE_REG_RELU_SUPPORTED
#define TFLITE_REG_RESHAPE_SUPPORTED
#define TFLITE_REG_SUB_SUPPORTED

#endif  // TFLITE_OPS_TO_REGISTER_H_
